"""change user id to uuid

Revision ID: f64e3e341a4e
Revises: 170521ba08f4
Create Date: 2026-08-31 20:14:22.443918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64e3e341a4e'
down_revision: Union[str, Sequence[str], None] = '170521ba08f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
